### ISSUE TITLE
Cud version, dlg_dir

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_backup_file#21]
Cud version:
call "..." button, to browse dir,
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_backup_file/cd_bk.py", line 633, in dlg_config
    fold    = CdSw.dlg_dir('')
  File "/home/user/cuda/cuda/app/py/cuda_backup_file/cd_plug_lib.py", line 716, in dlg_dir
    return dlg_dir(init_dir)
NameError: name 'dlg_dir' is not defined
```

**Comment by kvichans** [comment]
Повторил
