### ISSUE TITLE
ошибка при сравнении

### ISSUE THREAD

**Issue by ildarkhasanshin** [kvichans/cuda_backup_file#24]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ildar/.config/cudatext/py/cuda_backup_file/cd_bk.py", line 342, in copy_bk_or_compare
    subprocess.Popen(diff, shell=vrn_data['dfsh'])
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'diff -u "/home/ildar/1/index_190123032518.php" "/home/ildar/1/index.php"': 'diff -u "/home/ildar/1/index_190123032518.php" "/home/ildar/1/index.php"'

cudatext 1.72
python 3.6.7
ubuntu 18.04 x64

![img-2019-01-23-03-33-10](https://user-images.githubusercontent.com/8765305/51569967-b40f5000-1ebf-11e9-8241-4cbaf1d73bbe.png)

**Comment by kvichans** [comment]
Какого из файлов не существует при вызове?
Работает 
`diff -u "/home/ildar/1/index_190123032518.php" "/home/ildar/1/index.php"`
при запуске руками из шела?

**Comment by Alexey-T** [comment]
вот этой строки не существует. см ошибку выше.
вы ее передаете в Popen()

**Comment by Alexey-T** [comment]
Popen вроде надо давать или строку (путь!!) или лист строк

**Comment by kvichans** [comment]
@Alexey-T  У меня-то этот же код работает каждый день.

Жду @ildarkhasanshin

**Comment by Alexey-T** [comment]
И него же ЛИнукс. у вас Вин

**Comment by Alexey-T** [comment]
Винда может понять не так как Лин

**Comment by kvichans** [comment]
см..

**Comment by ildarkhasanshin** [comment]
> Работает
diff -u "/home/ildar/1/index_190123032518.php" "/home/ildar/1/index.php"
при запуске руками из шела?

да
